### PR TITLE
RXR-876 RXR-870 documentation

### PR DESCRIPTION
**Pull request by roninsightrx**
RXR-876: explore optimal default settings. I did some exploration using a PK and PK-PD model. The results are not fully consistent / clear, but I tried to boil down some of it to guidance that I included in a vignette (sampler-settings.Rmd). I also added several default settings that are slightly different from the CmdStanR defualts.

RXR-870: add documentation. Added model_syntax.Rmd, which is a rewrite from the Readme. I also rewrote two of the examples into vignettes.

### CODE REVIEW

**Review by karawoo — CHANGES_REQUESTED** [review]
The pkgdown github actions will fail because Torsten isn't installed. Can we install Torsten so the vignettes can run? Alternatively we could not evaluate the R code chunks, but if we can actually run everything I think that would be better. I can look into the github actions part if you want.

Also need to add `VignetteBuilder: knitr` to the DESCRIPTION.

**Comment by karawoo** [comment]
Maybe we should also skip the tests that require cmdstan if the path to cmdstan isn't set?

**Comment by roninsightrx** [comment]
Ah yes, didn't think of that. Torsten is a forked version of Stan with some additional C++ code. So Torsten has to be downloaded and compiled. Do you know how to set that up in GH actions?
Additionally, we also need to compile the `pkvancothomson` package (or remove the code that uses it). Can that be done?

**Comment by karawoo** [comment]
I've gotten Torsten built in github actions, but I'm getting an error running the vignette: https://github.com/InsightRX/PKPDposterior/runs/6838864679?check_suite_focus=true#step:8:226

I don't see the same error locally, will keep looking into it but lmk if you have any ideas.

**Comment by roninsightrx** [comment]
Made a fix, hopefully this solves the issue.

**Review by karawoo — APPROVED** [review]
Can you add `VignetteBuilder: knitr` to the DESCRIPTION file? Otherwise LGTM

**Comment by karawoo** [comment]
I recently learned that pkgdown will put a "get started" vignette in the nav bar if you save the file as `<pkgname>.Rmd`: https://pkgdown.r-lib.org/reference/build_articles.html#get-started

I implemented this for PKPDsim and I think it's nice having the getting started guide at the top level instead of under Articles:

Screen Shot 2022-06-17 at 4 14 33 PM

something to consider for PKPDposterior as well

**Pull request merged**
